### PR TITLE
Facebook login

### PR DESCRIPTION
**Pull request by emmanueljimawo**
I took a cue from the Google login that was initially done. Kindly review the code and advice on any necessary changes.

### CODE REVIEW

**Comment by emmanueljimawo** [comment]
I was able to rectify the issue with the facebook-login and also ensure that the user profile picture path gets stored on the database.

**Comment by anithaamarnath** [comment]
hi leave this branch and create a new branch from the top of the master and copy your Facebook code and then send us a Pull Request.

**Comment by anithaamarnath** [comment]
hi Emmanuel there is an issue 
**can you please leave this branch complete and create a new branch and do the facebook-login code** 
1. data is not storing in my psql database it says the internal server error 
2. can you please look into the scope  email and user_photos or  default in the Facebook developer console
3. Only we two can able to log in the Facebook because you give me permission. But when it comes to the production side it became a lot of trouble. Please read the Facebook developer docs

**Review by anithaamarnath — CHANGES_REQUESTED** [review]
hi Emmanuel there is an issue
can you please leave this branch complete and create a new branch and do the facebook-login code

data is not storing in my psql database it says the internal server error
can you please look into the scope email and user_photos or default in the Facebook developer console
Only we two can able to log in the Facebook because you give me permission. But when it comes to the production side it became a lot of trouble. Please read the Facebook developer docs

**Pull request closed without merging**
